FROM node:20-alpine as base

FROM base as builder

WORKDIR /home/node/app
COPY package*.json ./

ARG NEXT_PUBLIC_SERVER_URL
ARG NEXT_PUBLIC_IS_LIVE
ARG NEXT_PRIVATE_DRAFT_SECRET
ARG NEXT_PRIVATE_REVALIDATION_KEY
ARG NEXT_PUBLIC_PAYLOAD_URL

ENV NEXT_PUBLIC_SERVER_URL $NEXT_PUBLIC_SERVER_URL
ENV NEXT_PUBLIC_IS_LIVE $NEXT_PUBLIC_IS_LIVE
ENV NEXT_PRIVATE_DRAFT_SECRET $NEXT_PRIVATE_DRAFT_SECRET
ENV NEXT_PRIVATE_REVALIDATION_KEY $NEXT_PRIVATE_REVALIDATION_KEY
ENV NEXT_PUBLIC_PAYLOAD_URL $NEXT_PUBLIC_PAYLOAD_URL

COPY . .
RUN yarn install
RUN yarn build

FROM base as runtime

ENV NODE_ENV=production
ENV PAYLOAD_CONFIG_PATH=dist/payload.config.js

WORKDIR /home/node/app
COPY package*.json  ./
COPY yarn.lock ./

RUN yarn install --production
COPY --from=builder /home/node/app/dist ./dist
COPY --from=builder /home/node/app/build ./build

EXPOSE 3000

CMD ["node", "dist/server.js"]
