# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  - name: azureSubscription
    value: '934aebf4-852a-4d0a-8321-18504da210fc'

  # Web app name
  - name: webAppName
    value: 'cmbraga-payloadcms'

  # Environment name
  - name: environmentName
    value: 'cmbraga-payloadcms'

  # Agent VM image name
  - name: vmImageName
    value: 'ubuntu-latest'

  - group: build-variables


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        yarn
        yarn build
      displayName: 'yarn install and build'

    - task: CopyFiles@2
      displayName: Copy assets to TEMP
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          dist/**
          build/**
          node_modules/**
        TargetFolder: '$(Agent.TempDirectory)/sources'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Agent.TempDirectory)/sources'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifactName: 'drop'
        publishLocation: 'Container'
